// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeHkYD3XInTvPpYlofBShyebaFstoIeZ8',
    appId: '1:976479704040:web:77108228973ccf32590a5d',
    messagingSenderId: '976479704040',
    projectId: 'flutter-quiz-app-co',
    authDomain: 'flutter-quiz-app-co.firebaseapp.com',
    storageBucket: 'flutter-quiz-app-co.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj3BqQ3p1ggQpVl5SLb7CbZzcNIx9XK34',
    appId: '1:976479704040:android:38ddb5daca995f92590a5d',
    messagingSenderId: '976479704040',
    projectId: 'flutter-quiz-app-co',
    storageBucket: 'flutter-quiz-app-co.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Jc5pycVhNhNQMROxK8LCupIpdKfVHpw',
    appId: '1:976479704040:ios:25fae2baa3eee806590a5d',
    messagingSenderId: '976479704040',
    projectId: 'flutter-quiz-app-co',
    storageBucket: 'flutter-quiz-app-co.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Jc5pycVhNhNQMROxK8LCupIpdKfVHpw',
    appId: '1:976479704040:ios:25fae2baa3eee806590a5d',
    messagingSenderId: '976479704040',
    projectId: 'flutter-quiz-app-co',
    storageBucket: 'flutter-quiz-app-co.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeHkYD3XInTvPpYlofBShyebaFstoIeZ8',
    appId: '1:976479704040:web:8d407455262e1628590a5d',
    messagingSenderId: '976479704040',
    projectId: 'flutter-quiz-app-co',
    authDomain: 'flutter-quiz-app-co.firebaseapp.com',
    storageBucket: 'flutter-quiz-app-co.firebasestorage.app',
  );
}
